// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzgF3sMlguRjh-vl_OW2IHS2TOw7XdeE',
    appId: '1:1078119698934:web:be04f0340e39176fafb7d7',
    messagingSenderId: '1078119698934',
    projectId: 'kanban-468fd',
    authDomain: 'kanban-468fd.firebaseapp.com',
    storageBucket: 'kanban-468fd.firebasestorage.app',
    measurementId: 'G-R6X2D41F0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbif5yQbmGaNR5TwCLDtOoXqXrTHlUIPE',
    appId: '1:1078119698934:android:ecd57961e44f17a4afb7d7',
    messagingSenderId: '1078119698934',
    projectId: 'kanban-468fd',
    storageBucket: 'kanban-468fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL9ZJEWSe70URCVPAtr7xQ-M1PHkybPK8',
    appId: '1:1078119698934:ios:ce096857f849dc37afb7d7',
    messagingSenderId: '1078119698934',
    projectId: 'kanban-468fd',
    storageBucket: 'kanban-468fd.firebasestorage.app',
    androidClientId: '1078119698934-cqebk1udou1j8i580aha41jm5ai222i6.apps.googleusercontent.com',
    iosClientId: '1078119698934-nag1ubrmmnopstlf8lagdh5v2ofsua5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL9ZJEWSe70URCVPAtr7xQ-M1PHkybPK8',
    appId: '1:1078119698934:ios:ce096857f849dc37afb7d7',
    messagingSenderId: '1078119698934',
    projectId: 'kanban-468fd',
    storageBucket: 'kanban-468fd.firebasestorage.app',
    androidClientId: '1078119698934-cqebk1udou1j8i580aha41jm5ai222i6.apps.googleusercontent.com',
    iosClientId: '1078119698934-nag1ubrmmnopstlf8lagdh5v2ofsua5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqzgF3sMlguRjh-vl_OW2IHS2TOw7XdeE',
    appId: '1:1078119698934:web:414d13b415b7cd8aafb7d7',
    messagingSenderId: '1078119698934',
    projectId: 'kanban-468fd',
    authDomain: 'kanban-468fd.firebaseapp.com',
    storageBucket: 'kanban-468fd.firebasestorage.app',
    measurementId: 'G-59WPLS4QL5',
  );

}